Repository Anwishta/ShopSphere, pull requests merged in 2025-02, with the labels that each got.

#184 Improve error message on distributor login page
  frontend/src/pages/Auth/DistributorLogin.jsx
Labels: bug, good first issue, SWOC, BEGINNER

#185 Implement Dark/Light Mode for Sidebar & Footer
  frontend/src/components/Footer.jsx
  frontend/src/pages/Auth/Navigation.jsx
Labels: enhancement, SWOC, INTERMEDIATE, IWOC2025, Medium

#189 Add toast error for submitting empty form
  frontend/src/components/Contact.jsx
Labels: bug, SWOC, BEGINNER

#188 Dark Mode and Light Mode for Signup for distributor and customer, Login for distributor and customer
  frontend/src/pages/Auth/DistributorLogin.jsx
  frontend/src/pages/Auth/DistributorRegister.jsx
  frontend/src/pages/Auth/Login.jsx
  frontend/src/pages/Auth/Register.jsx
Labels: enhancement, SWOC, INTERMEDIATE, IWOC2025, Medium

#190 Cart bug fix
  backend/controllers/cartController.js
  backend/routes/cartRoutes.js
  frontend/src/components/Cart.jsx
  frontend/src/pages/Products/Product.jsx
  frontend/src/pages/redux/api/cartSlice.js
Labels: bug, SWOC, BEGINNER, IWOC2025, Easy

#191 Improve Contact Us error message
  frontend/src/components/Contact.jsx
Labels: enhancement, SWOC, BEGINNER

#193 404 page added
  frontend/src/components/UnderConstruction.jsx
  frontend/src/index.css
  frontend/src/main.jsx
Labels: enhancement, SWOC, BEGINNER, IWOC2025, Easy

#194 Cart Page UI
  frontend/src/components/Cart.jsx
Labels: enhancement, SWOC, INTERMEDIATE, IWOC2025, Medium

#195 Implement Blogs Page for Users
  backend/routes/blogRoutes.js
  frontend/src/main.jsx
  frontend/src/pages/Blog/BlogDetails.jsx
  frontend/src/pages/Blog/BlogList.jsx
  frontend/src/pages/Blog/CreateBlogModal.jsx
  frontend/src/pages/redux/api/blogApiSlice.js
  frontend/src/pages/redux/constants.js
Labels: enhancement, SWOC, ADVANCE, IWOC2025, Hard

#200 Update README.md
  README.md
Labels: bug, IWOC2025, Easy

#203 Fix pointer issue on favorite page
  frontend/src/pages/Products/Favorites.jsx
Labels: bug, SWOC, BEGINNER

#207 Blog Page UI
  frontend/src/pages/Blog/BlogDetails.jsx
Labels: enhancement, SWOC, INTERMEDIATE, IWOC2025, Medium

#206 Favorite Page Dark-Light Mode
  frontend/src/pages/Products/Favorites.jsx
Labels: enhancement, SWOC, INTERMEDIATE, IWOC2025, Medium

#210 Added code of conduct file
  CODE OF CONDUCT.md
Labels: documentation, IWOC2025, Easy

#214 Feat: Added an Our Services Section to the Home Page
  frontend/package-lock.json
  frontend/src/components/OurServices.jsx
  frontend/src/pages/Home.jsx
  frontend/tailwind.config.js
Labels: enhancement, SWOC, INTERMEDIATE

#212 Product Page
  backend/models/productModel.js
  frontend/src/pages/Products/ProductDetails.jsx
  frontend/src/pages/Shop/Shop.jsx
Labels: enhancement, SWOC, ADVANCE, IWOC2025, Hard

#209 Update Contributors.jsx
  frontend/src/pages/Contributors/Contributors.jsx
Labels: enhancement, SWOC, INTERMEDIATE

#226 Lazy Loading Added
  frontend/src/App.jsx
  frontend/src/main.jsx
Labels: enhancement, SWOC, INTERMEDIATE, IWOC2025, Medium

#227 Backend Support for Liking Blogs
  backend/controllers/blogController.js
  backend/models/blogModel.js
  backend/routes/blogRoutes.js
Labels: enhancement, SWOC, INTERMEDIATE, IWOC2025, Medium

#230 Delete User Account Backend
  backend/controllers/userController.js
  backend/models/userModel.js
  backend/package-lock.json
  backend/package.json
  backend/routes/userRoutes.js
  backend/utils/sendEmail.js
Labels: enhancement, SWOC, ADVANCE, IWOC2025, Hard

#235 Delete User Frontend
  .env.sample
  backend/controllers/userController.js
  backend/utils/sendEmail.js
  frontend/src/components/Modal.jsx
  frontend/src/main.jsx
  frontend/src/pages/Auth/VerifyDeletion.jsx
  frontend/src/pages/User/Profile.jsx
  frontend/src/pages/redux/api/userApiSlice.js
Labels: enhancement, SWOC, ADVANCE, IWOC2025, Hard

#243 Allow Users to Add Comments (Backend)
  backend/controllers/commentController.js
  backend/index.js
  backend/models/blogModel.js
  backend/models/commentModel.js
  backend/routes/commentRoutes.js
Labels: enhancement, SWOC, ADVANCE

#244 Light Mode in BlogList Page
  frontend/src/index.css
  frontend/src/pages/Blog/BlogList.jsx
  frontend/src/pages/Blog/CreateBlogModal.jsx
Labels: enhancement, SWOC, INTERMEDIATE, IWOC2025, Medium

#245 Frontend Implementation for User Comments
  frontend/src/pages/Blog/BlogDetails.jsx
  frontend/src/pages/redux/api/blogApiSlice.js
  frontend/src/pages/redux/constants.js
Labels: enhancement, SWOC, ADVANCE, IWOC2025, Hard

#246 Enable Multiple Image Uploads for Product Listings
  backend/controllers/productController.js
  backend/models/productModel.js
  backend/routes/productRoutes.js
  backend/utils/cloudinary.utils.js
  frontend/src/pages/Products/ProductDetails.jsx
  frontend/src/pages/Shop/Shop.jsx
  frontend/src/pages/redux/api/productApiSlice.js
Labels: enhancement, SWOC, ADVANCE, IWOC2025, Hard

#248 UI improve of services cards section
  frontend/src/components/OurServices.jsx
Labels: enhancement, SWOC, INTERMEDIATE, IWOC2025, Medium

#249 Fix scroll issue on Terms and Conditions page
  frontend/src/pages/Footer/TermsAndConditions.jsx
Labels: bug, SWOC, BEGINNER

#251 Show Similar Products Based on Category on Product Page
  backend/controllers/categoryController.js
  backend/controllers/productController.js
  backend/routes/productRoutes.js
  frontend/src/pages/Products/ProductDetails.jsx
  frontend/src/pages/redux/api/productApiSlice.js
Labels: enhancement, SWOC, ADVANCE, IWOC2025, Hard

#255 UI improve of footer
  frontend/src/components/Footer.jsx
Labels: enhancement, SWOC, INTERMEDIATE, IWOC2025, Medium

#253 Fix mode change bug on Terms and Conditions page
  frontend/src/pages/Footer/TermsAndConditions.jsx
Labels: bug, SWOC, BEGINNER

#252 Allow Users to Add Reviews for Products (Backend)
  backend/controllers/productController.js
  backend/models/productModel.js
  backend/routes/productRoutes.js
Labels: enhancement, SWOC, INTERMEDIATE, IWOC2025, Medium

#270 Product Review
  frontend/src/pages/Products/ProductDetails.jsx
  frontend/src/pages/redux/api/productApiSlice.js
Labels: SWOC, INTERMEDIATE, IWOC2025, Medium

#271 Forgot Password Functionality (Backend)
  backend/controllers/userController.js
  backend/models/userModel.js
  backend/routes/userRoutes.js
Labels: enhancement, SWOC, INTERMEDIATE, IWOC2025, Medium

#272 Image Upload Functionality for Blog Creation
  backend/controllers/blogController.js
  backend/models/blogModel.js
  backend/routes/blogRoutes.js
  frontend/src/pages/Blog/BlogDetails.jsx
  frontend/src/pages/Blog/BlogList.jsx
  frontend/src/pages/Blog/CreateBlogModal.jsx
  frontend/src/pages/redux/api/blogApiSlice.js
Labels: enhancement, SWOC, INTERMEDIATE, IWOC2025, Medium

#273 Add Blog Sorting and Filtering Functionality
  backend/controllers/blogController.js
  frontend/src/pages/Blog/BlogList.jsx
  frontend/src/pages/redux/api/blogApiSlice.js
Labels: enhancement, SWOC, ADVANCE, IWOC2025, Hard

#279 Star Rating Review System for Product
  backend/controllers/productController.js
  backend/models/productModel.js
  frontend/src/pages/Products/ProductDetails.jsx
  frontend/src/pages/Products/StarDisplay.jsx
  frontend/src/pages/Products/StarRating.jsx
  frontend/src/pages/redux/api/productApiSlice.js
Labels: enhancement, SWOC, ADVANCE, IWOC2025, Hard

#278 Enable Dot Scrolling Navigation in Dark Mode for Banner Carousel
  frontend/src/components/carousel.jsx
  frontend/src/pages/Offer/banners.jsx
Labels: enhancement, SWOC, INTERMEDIATE

#280 User Profile Page
  backend/controllers/userController.js
  frontend/src/pages/User/Profile.jsx
Labels: enhancement, SWOC, ADVANCE, IWOC2025, Hard

#281 Save For Later Backend
  backend/controllers/saveController.js
  backend/index.js
  backend/models/saveModel.js
  backend/routes/saveRoutes.js
Labels: enhancement, SWOC, INTERMEDIATE, IWOC2025, Medium

#282 Search Product Functionality
  backend/controllers/productController.js
  frontend/src/pages/Shop/SearchBar.jsx
  frontend/src/pages/Shop/Shop.jsx
  frontend/src/pages/redux/api/productApiSlice.js
Labels: enhancement, SWOC, ADVANCE, IWOC2025, Hard

#283 Edit Article Functionality (Backend)
  backend/controllers/blogController.js
  backend/routes/blogRoutes.js
  backend/utils/cloudinary.utils.js
Labels: enhancement, SWOC, INTERMEDIATE, IWOC2025, Medium

#285 Ensure Proper display of Specialshop page
  frontend/src/pages/SplShop/SplShop.jsx
Labels: bug, SWOC, BEGINNER

#286 Added Category Filter for Product
  backend/controllers/categoryController.js
  backend/routes/categoryRoutes.js
  frontend/src/main.jsx
  frontend/src/pages/Shop/CategoryFilter.jsx
  frontend/src/pages/Shop/Shop.jsx
Labels: enhancement, SWOC, ADVANCE, IWOC2025, Hard

#288 Added Article Deletion Functionality
  backend/controllers/blogController.js
  backend/routes/blogRoutes.js
Labels: enhancement, SWOC, INTERMEDIATE, IWOC2025, Medium

#289 Added circular progress to scroll to button
  frontend/package-lock.json
  frontend/src/components/scrollbtn.jsx
  frontend/src/pages/Blog/BlogDetails.jsx
  frontend/src/pages/Blog/BlogList.jsx
  frontend/src/pages/Contributors/Contributors.jsx
  frontend/src/pages/FAQ.jsx
  frontend/src/pages/Footer/TermsAndConditions.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/Offer/index.jsx
  frontend/src/pages/Products/Favorites.jsx
  frontend/src/pages/Products/ProductDetails.jsx
  frontend/src/pages/Shipping.jsx
  frontend/src/pages/Shop/Shop.jsx
  frontend/src/pages/SplShop/SplShop.jsx
  frontend/src/pages/User/Profile.jsx
Labels: enhancement, SWOC, INTERMEDIATE

#291 Ensure Proper display of Contributor page
  frontend/src/pages/Contributors/Contributors.jsx
Labels: bug, SWOC, BEGINNER
