Repository Anwishta/ShopSphere, pull requests merged in 2025-01, with the labels that each got.

#22 Make the register page responsive #12
  frontend/src/pages/Auth/Register.jsx
Labels: enhancement, good first issue, SWOC, BEGINNER

#25 Make the sidebar responsive 4
  frontend/src/pages/Auth/Navigation.css
  frontend/src/pages/Auth/Navigation.jsx
Labels: enhancement, SWOC, Level 1, BEGINNER

#27 updated UI & responsiveness for Register.jsx & Login.jsx
  frontend/src/Utils/constants.jsx
  frontend/src/pages/Auth/Login.jsx
  frontend/src/pages/Auth/Register.jsx
  frontend/vite.config.js
Labels: enhancement, SWOC, Level 3, ADVANCE

#36 Update AdminMenu.jsx
  frontend/src/pages/Admin/AdminMenu.jsx
Labels: enhancement, SWOC, INTERMEDIATE

#40 Update ProductList.jsx
  frontend/src/pages/Admin/ProductList.jsx
Labels: enhancement, SWOC, Level 2, INTERMEDIATE

#41 Fixed #15 Frontend and Backend Communication Failure due to CORS policy
  backend/index.js
Labels: bug, SWOC, INTERMEDIATE

#47 #3 Added Footer to Home
  backend/package-lock.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Footer.jsx
  frontend/src/pages/Home.jsx
Labels: enhancement, good first issue, SWOC, Level 1, BEGINNER

#57 Google authentication added for Signup and login
  backend/controllers/userController.js
  backend/models/userModel.js
  backend/package-lock.json
  backend/package.json
  backend/routes/userRoutes.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Utils/googleBtn.jsx
  frontend/src/firebaseConfig.js
  frontend/src/main.jsx
  frontend/src/pages/Auth/Login.jsx
  frontend/src/pages/Auth/Register.jsx
  frontend/src/pages/redux/api/userApiSlice.js
  package-lock.json
  package.json
Labels: enhancement, SWOC, Level 2, INTERMEDIATE

#60 Confirm password input box value is not hidden and eye icon not available #58
  frontend/src/pages/Auth/Register.jsx
Labels: enhancement, SWOC, BEGINNER

#62 added the cart component with default data
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Button.jsx
  frontend/src/components/Cart.jsx
  frontend/src/components/Input.jsx
  frontend/src/main.jsx
Labels: enhancement, SWOC, INTERMEDIATE

#63 Loding added during registration
  backend/package-lock.json
  frontend/src/pages/Auth/Login.jsx
  frontend/src/pages/Auth/Register.jsx
Labels: enhancement, SWOC, BEGINNER

#76 [⚠️Error Fix] Fixed Allowed Origins not having latest deployment Origin URL
  .env.sample
  backend/middleware/cors.js
Labels: bug, SWOC, Level 2, INTERMEDIATE

#78 Added FAQ section page
  frontend/src/components/Footer.jsx
  frontend/src/main.jsx
  frontend/src/pages/FAQ.jsx
Labels: enhancement, SWOC, Level 2, INTERMEDIATE

#79 Added newsletter subscription frontend
  frontend/src/components/NewsLetter.jsx
  frontend/src/pages/Home.jsx
Labels: enhancement, SWOC, Level 2, INTERMEDIATE

#82 Footer enhancement/adding contactus
  frontend/src/Utils/constants.jsx
  frontend/src/components/Contact.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/NewsLetter.jsx
  frontend/src/main.jsx
  frontend/src/pages/Home.jsx
Labels: enhancement, SWOC, Level 2, INTERMEDIATE

#84 Added favorite functionality
  frontend/src/App.jsx
  frontend/src/pages/Products/Favorites.jsx
  frontend/src/pages/Products/HeartIcon.jsx
  frontend/src/pages/Shop/Shop.jsx
  frontend/src/pages/SplShop/SplShop.jsx
  frontend/src/pages/redux/features/favorites/favoriteSlice.js
  frontend/src/pages/redux/store.js
Labels: enhancement, SWOC, Level 3, ADVANCE

#85 Enhancement: Add Terms and Conditions Section to Footer #72
  frontend/src/components/Footer.jsx
  frontend/src/main.jsx
  frontend/src/pages/Footer/TermsAndConditions.jsx
Labels: enhancement, SWOC, Level 3, ADVANCE

#88 Added Contribution list
  README.md
Labels: documentation, SWOC, Level 1, BEGINNER

#90 animations added + newsletter adjusted into footer
  frontend/src/components/Footer.jsx
  frontend/src/pages/Auth/Login.jsx
  frontend/src/pages/Auth/Register.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/Shop/Shop.jsx
  frontend/src/pages/SplShop/SplShop.jsx
Labels: enhancement, SWOC, Level 2, INTERMEDIATE

#95 [📄Docs]: Added Contribution Guidelines and Security Policy
  .github/SECURITY.md
  Contribution.md
Labels: documentation, SWOC, Level 2, INTERMEDIATE

#102 [📄Docs]: Added ISSUE and PULL REQUEST templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/PULL_REQUEST_TEMPLATE/bugfix_pull_request.md
  .github/PULL_REQUEST_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation, SWOC, Level 2, INTERMEDIATE

#100 Added Backend to create a blog
  backend/controllers/blogController.js
  backend/controllers/userController.js
  backend/index.js
  backend/models/blogModel.js
  backend/models/userModel.js
  backend/routes/blogRoutes.js
Labels: enhancement, SWOC, Level 3, ADVANCE

#104 feature-offer-page initalized
  frontend/package-lock.json
  frontend/package.json
  frontend/public/category/accessories.png
  frontend/public/category/beauty.png
  frontend/public/category/electronic.jpg
  frontend/public/category/fashion.png
  frontend/public/category/fitness.png
  frontend/public/category/footwear.png
  frontend/public/category/sports.jpg
  frontend/public/data.json
  frontend/public/images/backpack.jpg
  frontend/public/images/banner1.jpg
  frontend/public/images/banner2.png
  frontend/public/images/baseball-cap.jpg
  frontend/public/images/beautrry.jpg
  frontend/public/images/cream.jpg
  frontend/public/images/cream4.jpg
  frontend/public/images/earbuds.png
  frontend/public/images/fitness.jpg
  frontend/public/images/footwear-banner.jpg
  frontend/public/images/footwear.png
  frontend/public/images/handbag.jpg
  frontend/public/images/inag.png
  frontend/public/images/jacket.jpg
  frontend/public/images/laptop.jpg
  frontend/public/images/leather-wallet.jpg
  frontend/public/images/luxury-watch.jpg
  frontend/public/images/perfume.jpg
  frontend/public/images/running-shoes.jpg
  frontend/public/images/smartphone.jpg
  frontend/public/images/sneakers.png
  frontend/public/images/sunglasses.jpg
  frontend/public/images/treadmill.jpg
  frontend/public/images/tshirt.jpg
  frontend/public/images/watch.jpg
  frontend/public/images/wireless-earbuds.jpg
  frontend/public/images/yoga-mat.jpg
  frontend/public/offer/index.png
  frontend/public/offer/mobile.jpg
  frontend/public/offer/shoes.jpg
  frontend/public/product.json
  frontend/src/App.jsx
  frontend/src/Utils/discunt-price.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/card1.jsx
  frontend/src/components/card2.jsx
  frontend/src/components/card3.jsx
  frontend/src/components/carousel.jsx
  frontend/src/components/like-button.jsx
  frontend/src/components/product-wrapper.jsx
  frontend/src/components/star-rating.jsx
  frontend/src/index.css
  frontend/src/main.jsx
  frontend/src/pages/Offer/banners.jsx
  frontend/src/pages/Offer/category.jsx
  frontend/src/pages/Offer/index.jsx
  frontend/src/pages/Products/Favorites.jsx
  frontend/src/pages/Products/HeartIcon.jsx
Labels: enhancement, SWOC, Level 3, ADVANCE

#105 [📄docs] Fixed Templates of Pull Request Not Functioning
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE/bugfix_pull_request.md
  .github/PULL_REQUEST_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: enhancement, SWOC, Level 1, BEGINNER

#111 Added blur
  frontend/src/pages/Auth/Login.jsx
  frontend/src/pages/Auth/Register.jsx
Labels: enhancement, SWOC, Level 1, BEGINNER

#112 Added paypal payment
  .env.sample
  frontend/index.html
  frontend/src/components/Cart.jsx
  frontend/src/components/paypal.jsx
Labels: enhancement, SWOC, Level 2, INTERMEDIATE

#119 Added Cursor Trails
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/Utils/Cursor.jsx
  frontend/src/pages/Home.jsx
Labels: enhancement, SWOC, Level 2, INTERMEDIATE

#125 offer-button-bug-fix
  frontend/src/components/card2.jsx
Labels: enhancement, SWOC, Level 1, BEGINNER

#126 Remove the button inside the quantity box
  frontend/src/components/Cart.jsx
  frontend/src/index.css
Labels: bug, SWOC, Level 1, BEGINNER

#130 Added hover effects to Improve Offers Page
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/card1.jsx
  frontend/src/components/card2.jsx
  frontend/src/components/card3.jsx
  frontend/src/pages/Offer/category.jsx
  package-lock.json
  package.json
Labels: enhancement, SWOC, Level 2, INTERMEDIATE

#134 Add filter in favorites page
  frontend/src/pages/Products/Favorites.jsx
Labels: enhancement, SWOC, Level 1, BEGINNER

#118 Creating blog 97
  backend/controllers/blogController.js
  backend/routes/blogRoutes.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/main.jsx
  frontend/src/pages/Auth/Navigation.jsx
  frontend/src/pages/Blog/BlogList.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/redux/api/blogApiSlice.js
  frontend/src/pages/redux/constants.js
Labels: SWOC, ADVANCE

#142 Signup & Login as Distributor – Backend
  backend/controllers/userController.js
  backend/middleware/authMiddleware.js
  backend/models/userModel.js
  backend/routes/userRoutes.js
  backend/utils/cloudinary.utils.js
Labels: enhancement, SWOC, Level 3, ADVANCE

#137 Cart functionality
  .gitignore
  backend/config/db.js
  backend/controllers/cartController.js
  backend/controllers/productController.js
  backend/index.js
  backend/logs/app.log
  backend/models/cartModel.js
  backend/routes/cartRoutes.js
  backend/routes/productRoutes.js
  backend/utils/cloudinary.utils.js
  frontend/package-lock.json
  frontend/src/components/Cart.jsx
  frontend/src/main.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/Shop/Shop.jsx
  frontend/src/pages/redux/api/cartSlice.js
  frontend/src/pages/redux/constants.js
Labels: SWOC, INTERMEDIATE

#144 Signup & Login as Distributor – Frontend #139
  backend/controllers/userController.js
  frontend/src/main.jsx
  frontend/src/pages/Auth/DistributorLogin.jsx
  frontend/src/pages/Auth/DistributorRegister.jsx
  frontend/src/pages/Auth/Login.jsx
  frontend/src/pages/Auth/Register.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/redux/api/userApiSlice.js
Labels: enhancement, SWOC, Level 3, ADVANCE

#146 Add Product Backend
  backend/controllers/productController.js
  backend/middleware/authMiddleware.js
  backend/models/productModel.js
  backend/routes/productRoutes.js
  backend/utils/cloudinary.utils.js
  frontend/package-lock.json
Labels: SWOC, Level 3, ADVANCE

#147 Forgot password feature
  backend/Python: Flask Backend.py
  frontend/HTML: Forgot Password Form.html
Labels: enhancement, SWOC, Level 2, INTERMEDIATE

#149 Improve error message on Login page
  frontend/src/pages/Auth/Login.jsx
Labels: bug, SWOC, Level 1, BEGINNER

#153 🛑 Revert "Forgot password feature" 🛑
  backend/Python: Flask Backend.py
  frontend/HTML: Forgot Password Form.html
Labels: bug, SWOC, Level 1, BEGINNER

#159 Improve error message on sign-up page
  frontend/src/pages/Auth/Login.jsx
  frontend/src/pages/Auth/Register.jsx
Labels: SWOC, BEGINNER

#163 Improve error message on distributor signup page
  frontend/src/pages/Auth/DistributorRegister.jsx
Labels: enhancement, good first issue, SWOC, Level 1, BEGINNER

#165 Feature/dynamic contributors page
  backend/package-lock.json
  frontend/package-lock.json
  frontend/src/pages/Contributors/Contributors.jsx
Labels: enhancement, SWOC, Level 2, INTERMEDIATE

#166 Favorite Product Bug Fixed
  frontend/src/pages/Products/HeartIcon.jsx
  frontend/src/pages/Shop/Shop.jsx
  frontend/src/pages/redux/features/favorites/favoriteSlice.js
Labels: bug, good first issue, SWOC, Level 1, BEGINNER

#180 Return & Refund Page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/main.jsx
  frontend/src/pages/Shipping.jsx
Labels: enhancement, SWOC, INTERMEDIATE

#181 improved profile section
  frontend/src/pages/User/Profile.jsx
Labels: enhancement, SWOC, INTERMEDIATE
